"""Optional OCR identities and recovery-path classification."""

from veriformis.ocr.identity import (
    ADMITTED_LANGUAGES,
    ADMITTED_PSM,
    LIMITATIONS,
    PREPROCESS_IDS,
    RECOVERY_PATHS,
    OcrBoundingBox,
    OcrConfidence,
    OcrEnginePin,
    OcrPageIdentity,
    OcrPreprocess,
    admitted_ocr_engine,
    build_ocr_page_identity,
    ocr_page_identity_id,
    require_ocr_recovery_not_executable,
)
from veriformis.ocr.recovery import (
    OcrPageRequest,
    OcrPageResult,
    PdfDocumentRecovery,
    PdfPageRecovery,
    document_recovery_path,
    page_kind,
    recover_pages,
)

__all__ = [
    "ADMITTED_LANGUAGES",
    "ADMITTED_PSM",
    "LIMITATIONS",
    "PREPROCESS_IDS",
    "RECOVERY_PATHS",
    "OcrBoundingBox",
    "OcrConfidence",
    "OcrEnginePin",
    "OcrPageIdentity",
    "OcrPageRequest",
    "OcrPageResult",
    "OcrPreprocess",
    "PdfDocumentRecovery",
    "PdfPageRecovery",
    "admitted_ocr_engine",
    "build_ocr_page_identity",
    "document_recovery_path",
    "ocr_page_identity_id",
    "page_kind",
    "recover_pages",
    "require_ocr_recovery_not_executable",
]
