"""Existing-dataset mapping: compiler-path modes, contracts, and JSONL execution."""

from veriformis.mapping.capture import JsonlCapture, capture_jsonl
from veriformis.mapping.detect import (
    confirm_mapping_plan,
    detect_mapping,
    mapping_confirmation_digest,
    mapping_detector_catalog,
    mapping_detector_catalog_json,
)
from veriformis.mapping.execute import execute_mapping, replay_mapping
from veriformis.mapping.finish import (
    FinishedImportPlan,
    ImportedCurationResult,
    ImportedRowSet,
    ImportedSplitResult,
    ImportedValidationReport,
    curate_imported_records,
    serialize_imported_records,
    split_imported_records,
    validate_imported_dataset,
)
from veriformis.mapping.models import (
    ADMITTED_CONTAINERS,
    COERCION_RULES,
    CONTRACT_DATA_NAME,
    FieldMapping,
    ImportedField,
    ImportedRecord,
    MappedValueEvidence,
    MappingPlan,
    RESERVED_CONTAINERS,
    ROW_SCHEMA_PAYLOAD_KEYS,
    RowSource,
    mapping_contract_discovery,
    mapping_contract_discovery_json,
)
from veriformis.mapping.modes import (
    DATASET_ROW_MODE,
    DOCUMENT_SOURCE_MODE,
    IMPLEMENTED_INPUT_MODES,
    INPUT_MODE_IDS,
    MIXED_MODE,
    MODE_DATA_NAME,
    PLANNED_INPUT_MODES,
    InputMode,
    InputModeCatalog,
    discover_modes,
    input_mode_catalog,
    input_mode_catalog_json,
    require_executable_mode,
)
from veriformis.mapping.result import (
    MAPPING_STAGE_SCHEMA_ID,
    MappingRecipe,
    MappingResult,
    ROW_JSONL_PARSER_ID,
    ROW_JSONL_PARSER_VERSION,
)

__all__ = [
    "ADMITTED_CONTAINERS",
    "COERCION_RULES",
    "CONTRACT_DATA_NAME",
    "FieldMapping",
    "ImportedField",
    "ImportedRecord",
    "MappedValueEvidence",
    "MappingPlan",
    "RESERVED_CONTAINERS",
    "ROW_SCHEMA_PAYLOAD_KEYS",
    "RowSource",
    "mapping_contract_discovery",
    "mapping_contract_discovery_json",
    "DATASET_ROW_MODE",
    "DOCUMENT_SOURCE_MODE",
    "IMPLEMENTED_INPUT_MODES",
    "INPUT_MODE_IDS",
    "MIXED_MODE",
    "MODE_DATA_NAME",
    "PLANNED_INPUT_MODES",
    "InputMode",
    "InputModeCatalog",
    "discover_modes",
    "input_mode_catalog",
    "input_mode_catalog_json",
    "require_executable_mode",
    "JsonlCapture",
    "capture_jsonl",
    "confirm_mapping_plan",
    "detect_mapping",
    "mapping_confirmation_digest",
    "mapping_detector_catalog",
    "mapping_detector_catalog_json",
    "execute_mapping",
    "replay_mapping",
    "MAPPING_STAGE_SCHEMA_ID",
    "MappingRecipe",
    "MappingResult",
    "ROW_JSONL_PARSER_ID",
    "ROW_JSONL_PARSER_VERSION",
    "FinishedImportPlan",
    "ImportedCurationResult",
    "ImportedRowSet",
    "ImportedSplitResult",
    "ImportedValidationReport",
    "curate_imported_records",
    "serialize_imported_records",
    "split_imported_records",
    "validate_imported_dataset",
]
