"""Integrity-bearing, deterministic training-dataset construction."""

from veriformis.errors import ConstructionError

from .evidence import (
    IRArtifactKind,
    IRFieldEncoding,
    IRFieldEvidence,
    make_ir_field_evidence,
    resolve_ir_field_evidence,
)
from .models import (
    BUILTIN_CONSTRUCTOR_IDS,
    CONSTRUCTION_GATES,
    OBJECTIVE_FIELD_CONTRACTS,
    V1_CONSTRUCTION_DIAGNOSTIC_CODES,
    V1_PROMOTION_REASON_CODES,
    CandidateRecord,
    ConstructionDiagnostic,
    ConstructionPass,
    ConstructionResult,
    DatasetRecipe,
    DatasetRecord,
    PromotionDecision,
    RecordField,
    ReviewEvidence,
    SegmentationPolicy,
    SourceTextEvidence,
    TrainingObjective,
    construction_result_from_dict,
    construction_result_from_json_bytes,
    construction_result_to_dict,
    dataset_recipe_from_dict,
    dataset_recipe_from_json_bytes,
    dataset_recipe_to_dict,
)
from .pipeline import (
    ConstructionInputs,
    IRArtifactInput,
    construct_dataset,
    validate_construction_result,
)

__all__ = [
    "BUILTIN_CONSTRUCTOR_IDS",
    "CONSTRUCTION_GATES",
    "OBJECTIVE_FIELD_CONTRACTS",
    "V1_CONSTRUCTION_DIAGNOSTIC_CODES",
    "V1_PROMOTION_REASON_CODES",
    "CandidateRecord",
    "ConstructionDiagnostic",
    "ConstructionError",
    "ConstructionInputs",
    "ConstructionPass",
    "ConstructionResult",
    "DatasetRecipe",
    "DatasetRecord",
    "IRArtifactInput",
    "IRArtifactKind",
    "IRFieldEncoding",
    "IRFieldEvidence",
    "PromotionDecision",
    "RecordField",
    "ReviewEvidence",
    "SegmentationPolicy",
    "SourceTextEvidence",
    "TrainingObjective",
    "construct_dataset",
    "construction_result_from_dict",
    "construction_result_from_json_bytes",
    "construction_result_to_dict",
    "dataset_recipe_from_dict",
    "dataset_recipe_from_json_bytes",
    "dataset_recipe_to_dict",
    "make_ir_field_evidence",
    "resolve_ir_field_evidence",
    "validate_construction_result",
]
